version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: timesheet-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: timesheet-service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - timesheet-network

  # Timesheet Service
  timesheet-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timesheet-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # MongoDB Configuration
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/timesheet-service?authSource=admin
      
      # Application Configuration
      NODE_ENV: production
      PORT: 3001
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001
      
      # Rate Limiting
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    depends_on:
      - mongodb
    networks:
      - timesheet-network
    volumes:
      - ./logs:/app/logs

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:latest
    container_name: timesheet-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongodb
    networks:
      - timesheet-network

volumes:
  mongodb_data:
    driver: local

networks:
  timesheet-network:
    driver: bridge
